### PR TITLE
Update to latest apcupsd

### PR DESCRIPTION
**Pull request by crag-r**
New apcupsd package releasted with modbus protocol enabled

### CODE REVIEW

**Comment by korylprince** [comment]
Currently [v3.9 still has the `r0` package](https://pkgs.alpinelinux.org/packages?name=apcupsd&branch=v3.9). Once they pull `r1` into v3.9 or they release it in v3.10, I'll merge this.

You may be able to get them to drop it into v3.9 if you contact them on their mailing list.

Edit: looks like v3.10 is [supposed to be released on 05/01/2019](https://bugs.alpinelinux.org/versions/133).

**Comment by crag-r** [comment]
Sorry that's my fault I had edge selected when I filtered for the package, let's wait a week (or two!)

**Comment by crag-r** [comment]
Hi Kory, looks like r1 is out now in v3.10

**Comment by korylprince** [comment]
I've updated to 1.9 which includes this new package. However, the hassio base images haven't been updated to 3.10 yet, so the build fails. I've left a message on discord and as soon is the base images get updated, I'll build and push 1.9. Thanks.

**Comment by PrathikGopal** [comment]
Hi Kory, im trying the 1.9 build on rpi3b and see the below error on update. 

19-07-03 02:06:34 ERROR (SyncWorker_9) [hassio.docker.interface] Can't install korylprince/hassio-apcupsd-armv7:1.9 -> 404 Client Error: Not Found ("manifest for korylprince/hassio-apcupsd-armv7:1.9 not found").

**Comment by korylprince** [comment]
The hassio base images were updated, and I built and pushed 1.9. Thanks for keeping me updated on this @crag-r.

**Pull request closed without merging**
